/**
 * THE GATE (docs/app.md, phase 2). `poolId` and the position-id packing are tier-1 frozen and the
 * SDK computes both OFFLINE, with no RPC — so if the TypeScript and the Solidity ever disagree, a
 * client addresses the wrong pool or the wrong position, silently, with real funds behind it.
 *
 * These vectors are generated BY THE CONTRACT (`contracts/script/GenVectors.s.sol`), not written by
 * hand, so this is a genuine cross-implementation check rather than a restatement of the TS. If the
 * derivation changes — which is by definition a tier-1 event — regenerate them and this test tells
 * you exactly what moved.
 */

import { describe, expect, it } from "vitest";
import vectors from "../vectors/derivation-vectors.json" with { type: "json" };
import { poolId, type PoolKey } from "../src/keys.js";
import { claimId, claimToken, isPosition, NO_CAP, packFloorCap, positionId, unpackFloorCap } from "../src/ids.js";
import type { Address, Hex } from "viem";

interface Vector {
  base: string;
  quote: string;
  tickSpacing: string;
  phiMin: string;
  kappa: string;
  alpha: string;
  poolId: string;
  floor: string;
  cap: string;
  id: string;
}

const V = (vectors as { vectors: Vector[] }).vectors;

const keyOf = (v: Vector): PoolKey => ({
  base: v.base as Address,
  quote: v.quote as Address,
  tickSpacing: BigInt(v.tickSpacing),
  phiMin: BigInt(v.phiMin),
  kappa: BigInt(v.kappa),
  alpha: BigInt(v.alpha),
});

describe("derivation vectors from the contract", () => {
  it("has a non-trivial corpus", () => {
    // guard against a truncated or empty vector file silently making everything below vacuous
    expect(V.length).toBeGreaterThan(20);
    expect(new Set(V.map((v) => v.poolId)).size).toBeGreaterThan(1);
    expect(V.some((v) => BigInt(v.cap) !== NO_CAP)).toBe(true);
    expect(V.some((v) => BigInt(v.floor) < 0n)).toBe(true);
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: poolId matches PoolKeyLib.toId", (_i, v) => {
    expect(poolId(keyOf(v))).toBe(v.poolId as Hex);
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: positionId matches idOf", (_i, v) => {
    const got = positionId(v.poolId as Hex, BigInt(v.tickSpacing), BigInt(v.floor), BigInt(v.cap));
    expect(got).toBe(BigInt(v.id));
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: pack/unpack round-trips", (_i, v) => {
    const spacing = BigInt(v.tickSpacing);
    const packed = packFloorCap(spacing, BigInt(v.floor), BigInt(v.cap));
    const back = unpackFloorCap(spacing, packed);
    expect(back.floor).toBe(BigInt(v.floor));
    expect(back.capped).toBe(BigInt(v.cap) !== NO_CAP);
    if (back.capped) expect(back.cap).toBe(BigInt(v.cap));
  });

  it("every generated position id sets the namespace bit", () => {
    for (const v of V) expect(isPosition(BigInt(v.id))).toBe(true);
  });
});

describe("the id namespace", () => {
  it("separates positions from token claims on bit 255", () => {
    const token = "0x5f3f1dBD7B74C6B46e8c44f98792A1dAf8d69154" as Address;
    const cid = claimId(token);
    expect(isPosition(cid)).toBe(false);
    expect(claimToken(cid)?.toLowerCase()).toBe(token.toLowerCase());

    const pid = BigInt(V[0]!.id);
    expect(isPosition(pid)).toBe(true);
    // the thing an indexer must not get wrong: a position is NOT a claim on some token
    expect(claimToken(pid)).toBeNull();
  });
});

describe("off-grid inputs fail at the call site, not at the transaction", () => {
  const spacing = 10n ** 17n;
  const pid = V[0]!.poolId as Hex;

  it("rejects an off-grid floor", () => {
    expect(() => positionId(pid, spacing, spacing + 1n)).toThrow(/off-grid/);
  });

  it("rejects an off-grid cap", () => {
    expect(() => positionId(pid, spacing, spacing, 2n * spacing + 1n)).toThrow(/off-grid/);
  });

  it("rejects a cap at or below the floor", () => {
    expect(() => positionId(pid, spacing, 2n * spacing, 2n * spacing)).toThrow(/strictly above/);
  });
});
