import { bytea } from "../src/indexer.js";
import { annualise, edgeQuote, feesQuote, floorDistance, floorDrawdown, floorDrawdownPrice, floorPrice, lpEdge } from "../src/pools.js";
/**
 * THE GATE (docs/app.md, phase 2). `poolId` and the position-id packing are tier-1 frozen and the
 * SDK computes both OFFLINE, with no RPC — so if the TypeScript and the Solidity ever disagree, a
 * client addresses the wrong pool or the wrong position, silently, with real funds behind it.
 *
 * These vectors are generated BY THE CONTRACT (`contracts/script/GenVectors.s.sol`), not written by
 * hand, so this is a genuine cross-implementation check rather than a restatement of the TS. If the
 * derivation changes — which is by definition a tier-1 event — regenerate them and this test tells
 * you exactly what moved.
 */

import { describe, expect, it } from "vitest";
import vectors from "../vectors/derivation-vectors.json" with { type: "json" };
import { poolId, type PoolKey } from "../src/keys.js";
import { claimId, claimToken, isPosition, NO_CAP, packFloorCap, positionId, unpackFloorCap } from "../src/ids.js";
import type { Address, Hex } from "viem";

interface Vector {
  base: string;
  quote: string;
  tickSpacing: string;
  phiMin: string;
  kappa: string;
  alpha: string;
  poolId: string;
  floor: string;
  cap: string;
  id: string;
}

const V = (vectors as { vectors: Vector[] }).vectors;

const keyOf = (v: Vector): PoolKey => ({
  base: v.base as Address,
  quote: v.quote as Address,
  tickSpacing: BigInt(v.tickSpacing),
  phiMin: BigInt(v.phiMin),
  kappa: BigInt(v.kappa),
  alpha: BigInt(v.alpha),
});

describe("derivation vectors from the contract", () => {
  it("has a non-trivial corpus", () => {
    // guard against a truncated or empty vector file silently making everything below vacuous
    expect(V.length).toBeGreaterThan(20);
    expect(new Set(V.map((v) => v.poolId)).size).toBeGreaterThan(1);
    expect(V.some((v) => BigInt(v.cap) !== NO_CAP)).toBe(true);
    expect(V.some((v) => BigInt(v.floor) < 0n)).toBe(true);
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: poolId matches PoolKeyLib.toId", (_i, v) => {
    expect(poolId(keyOf(v))).toBe(v.poolId as Hex);
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: positionId matches idOf", (_i, v) => {
    const got = positionId(v.poolId as Hex, BigInt(v.tickSpacing), BigInt(v.floor), BigInt(v.cap));
    expect(got).toBe(BigInt(v.id));
  });

  it.each(V.map((v, i) => [i, v] as const))("vector %i: pack/unpack round-trips", (_i, v) => {
    const spacing = BigInt(v.tickSpacing);
    const packed = packFloorCap(spacing, BigInt(v.floor), BigInt(v.cap));
    const back = unpackFloorCap(spacing, packed);
    expect(back.floor).toBe(BigInt(v.floor));
    expect(back.capped).toBe(BigInt(v.cap) !== NO_CAP);
    if (back.capped) expect(back.cap).toBe(BigInt(v.cap));
  });

  it("every generated position id sets the namespace bit", () => {
    for (const v of V) expect(isPosition(BigInt(v.id))).toBe(true);
  });
});

describe("the id namespace", () => {
  it("separates positions from token claims on bit 255", () => {
    const token = "0x5f3f1dBD7B74C6B46e8c44f98792A1dAf8d69154" as Address;
    const cid = claimId(token);
    expect(isPosition(cid)).toBe(false);
    expect(claimToken(cid)?.toLowerCase()).toBe(token.toLowerCase());

    const pid = BigInt(V[0]!.id);
    expect(isPosition(pid)).toBe(true);
    // the thing an indexer must not get wrong: a position is NOT a claim on some token
    expect(claimToken(pid)).toBeNull();
  });
});

describe("off-grid inputs fail at the call site, not at the transaction", () => {
  const spacing = 10n ** 17n;
  const pid = V[0]!.poolId as Hex;

  it("rejects an off-grid floor", () => {
    expect(() => positionId(pid, spacing, spacing + 1n)).toThrow(/off-grid/);
  });

  it("rejects an off-grid cap", () => {
    expect(() => positionId(pid, spacing, spacing, 2n * spacing + 1n)).toThrow(/off-grid/);
  });

  it("rejects a cap at or below the floor", () => {
    expect(() => positionId(pid, spacing, 2n * spacing, 2n * spacing)).toThrow(/strictly above/);
  });
});

describe("denominated readouts", () => {
  const WAD = 10n ** 18n;
  // F = 2% per unit L, Sigma = 1%, L = 1,000,000 quote
  const s = {
    F: WAD / 50n,
    bigSigma: WAD / 100n,
    lActive: 1_000_000n * WAD,
    x: 0n,
    backstopFloor: -2n * (WAD / 10n), // floor at log -0.2
  };

  it("fees in quote are F times L, not F", () => {
    expect(feesQuote(s)).toBe(20_000n * WAD); // 2% of 1,000,000
  });

  it("edge in quote applies the same scaling to F - Sigma/2", () => {
    // 0.02 - 0.005 = 0.015 -> 15,000
    expect(edgeQuote(s)).toBe(15_000n * WAD);
    expect(edgeQuote(s)).toBe((lpEdge(s) * s.lActive) / WAD);
  });

  it("floor distance is x - xi, and the drawdown is its negation", () => {
    expect(floorDistance(s)).toBe(2n * (WAD / 10n));
    expect(floorDrawdown(s)).toBeCloseTo(-0.2, 12);
  });

  it("floor price and the arithmetic drawdown agree with exp", () => {
    expect(floorPrice(s)).toBeCloseTo(Math.exp(-0.2), 12);
    // a 0.2 log distance is an 18.1% price fall, not 20% — the gap the log measure hides
    expect(floorDrawdownPrice(s)).toBeCloseTo(Math.exp(-0.2) - 1, 12);
    expect(floorDrawdownPrice(s)).toBeCloseTo(-0.1813, 4);
  });

  it("annualises a realised rate over its own window", () => {
    const halfYear = 31_536_000n / 2n;
    expect(annualise(WAD / 50n, halfYear)).toBeCloseTo(0.04, 12); // 2% in 6 months -> 4%/yr
    expect(annualise(WAD / 50n, 31_536_000n)).toBeCloseTo(0.02, 12);
  });

  it("annualise is zero rather than infinite at zero elapsed", () => {
    expect(annualise(WAD, 0n)).toBe(0);
  });
});

describe("indexer bytea filtering", () => {
  it("converts an 0x hash to the \\x literal a bytea column filters on", () => {
    // The API RENDERS 0x… and FILTERS on \x… — passing back what it gave you matches nothing,
    // silently, because the query is valid and the comparison simply never holds.
    expect(bytea("0xdeadbeef")).toBe("\\xdeadbeef");
  });

  it("is idempotent on an already-bare hash", () => {
    expect(bytea("deadbeef" as `0x${string}`)).toBe("\\xdeadbeef");
  });
});
