/**
 * keys.ts — market identity, computed OFFLINE.
 *
 * A market is a `PoolKey`, and its id is the hash of that key. Both are **tier-1 frozen**
 * (docs/app.md): the key is in every keyed signature *and* `poolId = keccak256(abi.encode(key))`,
 * so adding a field would change every selector and re-identify every market, orphaning all
 * indexed history.
 *
 * This module reimplements `PoolKeyLib.toId` in TypeScript so a client can address a market with no
 * RPC at all. `test/derivation.test.ts` pins it against vectors generated by the contract itself —
 * if the two ever disagree, that test fails rather than the SDK silently addressing the wrong pool.
 */

import { encodeAbiParameters, keccak256, type Address, type Hex } from "viem";

/**
 * The economic tuple that IS the market. Field order is load-bearing: it is the ABI encoding order,
 * so it must match `src/types/PoolKey.sol` exactly.
 */
export interface PoolKey {
  base: Address;
  quote: Address;
  /** Log-tick spacing, WAD. The LP-boundary ladder — position floors and caps. */
  tickSpacing: bigint;
  /** Fee floor, WAD. `0n` selects `DEFAULT_FEE_MIN` (2 bp) at read time. */
  phiMin: bigint;
  /** Variance-fee coefficient, WAD. `0n` disables the dynamic fee. */
  kappa: bigint;
  /** EMA decay, WAD. `0n` selects `DEFAULT_ALPHA` (1/2) at read time. */
  alpha: bigint;
}

const POOL_KEY_ABI = [
  {
    type: "tuple",
    components: [
      { name: "base", type: "address" },
      { name: "quote", type: "address" },
      { name: "tickSpacing", type: "int256" },
      { name: "phiMin", type: "uint256" },
      { name: "kappa", type: "uint256" },
      { name: "alpha", type: "uint256" },
    ],
  },
] as const;

/**
 * `poolId = keccak256(abi.encode(key))` — the primary key of the entire read model.
 *
 * Note the zero-vs-default caveat the Solidity type documents: `phiMin` and `alpha` of `0` resolve
 * to their defaults at READ time, so a key carrying `0n` and one carrying the resolved default are
 * DIFFERENT markets with different ids, even though they behave identically. Always address a
 * market by the key it was initialized with.
 */
export function poolId(key: PoolKey): Hex {
  return keccak256(
    encodeAbiParameters(POOL_KEY_ABI, [
      {
        base: key.base,
        quote: key.quote,
        tickSpacing: key.tickSpacing,
        phiMin: key.phiMin,
        kappa: key.kappa,
        alpha: key.alpha,
      },
    ]),
  );
}

/** Structural equality of two keys — i.e. "the same market". */
export function sameMarket(a: PoolKey, b: PoolKey): boolean {
  return poolId(a) === poolId(b);
}
