/**
 * keys.ts — market identity, computed OFFLINE.
 *
 * A market is a `PoolKey`, and its id is the hash of that key. Both are **tier-1 frozen**
 * (docs/app.md): the key is in every keyed signature *and* `poolId = keccak256(abi.encode(key))`,
 * so adding a field would change every selector and re-identify every market, orphaning all
 * indexed history.
 *
 * This module reimplements `PoolKeyLib.toId` in TypeScript so a client can address a market with no
 * RPC at all. `test/derivation.test.ts` pins it against vectors generated by the contract itself —
 * if the two ever disagree, that test fails rather than the SDK silently addressing the wrong pool.
 */

import { encodeAbiParameters, keccak256, type Address, type Hex } from "viem";

/**
 * The economic tuple that IS the market. Field order is load-bearing: it is the ABI encoding order,
 * so it must match `src/types/PoolKey.sol` exactly.
 */
export interface PoolKey {
  base: Address;
  quote: Address;
  /** Log-tick spacing, WAD. The LP-boundary ladder — position floors and caps. */
  tickSpacing: bigint;
  /**
   * The swap fee, WAD, fixed for the life of the market: `FEE_MIN` (1 bp) ≤ φ ≤ `FEE_MAX` (25%),
   * or `0n`, which selects `DEFAULT_FEE` (2 bp) at read time. Four fields since C version 4
   * (decisions 042): `kappa` and `alpha` left with the variance kernel, and `phiMin` — a floor with
   * nothing above it — became `phi`. Every pool id changed with the shape.
   */
  phi: bigint;
}

const POOL_KEY_ABI = [
  {
    type: "tuple",
    components: [
      { name: "base", type: "address" },
      { name: "quote", type: "address" },
      { name: "tickSpacing", type: "int256" },
      { name: "phi", type: "uint256" },
    ],
  },
] as const;

/**
 * `poolId = keccak256(abi.encode(key))` — the primary key of the entire read model.
 *
 * Note the zero-vs-default caveat the Solidity type documents: a `phi` of `0` resolves to
 * `DEFAULT_FEE` at READ time, so a key carrying `0n` and one carrying the resolved default are
 * DIFFERENT markets with different ids, even though they behave identically. Always address a
 * market by the key it was initialized with.
 */
export function poolId(key: PoolKey): Hex {
  return keccak256(
    encodeAbiParameters(POOL_KEY_ABI, [
      {
        base: key.base,
        quote: key.quote,
        tickSpacing: key.tickSpacing,
        phi: key.phi,
      },
    ]),
  );
}

/** Structural equality of two keys — i.e. "the same market". */
export function sameMarket(a: PoolKey, b: PoolKey): boolean {
  return poolId(a) === poolId(b);
}
